language: node_js
node_js:
  - "12.11.1"
service: 
  - docker

before_install:
  - npm install

script:
  - npm run build
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t cuizhanshan1025/blog_new:latest .
  - docker push cuizhanshan1025/blog_new:latest